serializer: csv

db:
  default:
    database: testdb
    hostname: localhost
    username: root
    password: ""
  otherdb:
    database: testdb
    hostname: localhost
    username: root
    password: ""

tables:

  master:
    count: 5
    keep-samples:
      - id
    hints:
      id: autoincrement

  slave:
    count: 15
    keep-samples:
      - id
    foreign-keys: 
      master_id: master.id
      other_master_id: master.id 
    hints:
      id: autoincrement
